#!/usr/bin/env bash
# this for knowing the servers and names of theirs
sub() {
    if [ $# -lt 2 ]; then
        dig www.$1 | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print "The subdomain www is a "$4" record and points to "$5}'
        dig lb-01.$1 | grep -A1 'ANSWER SECTION:'| tail -n 1 | awk '{print "The subdomain lb-01 is a "$4" record and points to "$5}'
        dig web-01.$1 | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print "The subdomain web-01 is a "$4" record and points to "$5}'
        dig web-02.$1 | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print "The subdomain web-02 is a "$4" record and points to "$5}'
    else
        dig $2.$1 | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk -v prefix=$2 '{print "The subdomain "prefix" is a "$4" record and points to "$5}'
    fi
}
sub "$@"
