#!/usr/bin/env bash
# Write a Bash script that transfers a file from our client to a server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i 's/\blisten 80\b/listen 80;/g' /etc/nginx/sites-available/default
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo service nginx start
sudo nginx -s reload
