#!/usr/bin/env bash
# Write a Bash script that transfers a file from our client to a server
sudo apt-get update 
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo chmod 600 /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start