#!/usr/bin/env bash
# Write a Bash script that transfers a file from our client to a server
sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo chmod 600 /var/www/html/index.nginx-debian.html
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i '/^[^#]*server_name.*;$/a \ \n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=mN_jYKCTEwU&t=10s;\n\t}' /etc/nginx/sites-available/default
sudo service nginx start
sudo nginx -s reload
