#!/usr/bin/env bash
# this solve for custom https response header
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo sh -c 'echo "server {
    listen 80 default_server;

    root /var/www/html;
    index index.html index.htm;
	add_header X-Served-By $(hostname);
    server_name localhost;
    location / {
        try_files \$uri \$uri/ =404;
    }
}" > /etc/nginx/sites-available/default'
