#!/usr/bin/env bash
# this solve for custom https response hea
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello world!" > /var/www/html/index.html'
sudo sh -c 'printf "Ceci n'\''est pas une page\n" > /var/www/html/404.html'
sudo sed -i '/^[^#]*server_name.*;$/a \ \n\tlocation \/redirect_me {\n\t\treturn 301 https://www.linkedin.com/in/abeermosaad;\n\t}' /etc/nginx/sites-available/default
sudo sed -i '/^[^#]*server_name.*;$/a \ \n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\tinternal;\n\t\troot /var/www/abeermosaad.tech/html;\n\t}' /etc/nginx/sites-available/default
sudo sed -i "/^server {/a \ \tadd_header X-Served-By \($hostname);" /etc/nginx/sites-available/default
sudo echo "($hostname)"
sudo service nginx start
sudo nginx -s reload
