#!/usr/bin/env bash
# this pring Best School ten times
i=1
m=1
echo "Hour: 0"
while [ $i -le 779 ]
do
if [ $((i%60)) == 0 ]
then
echo -n "Hour: "
echo $(( $i / 60 ))
m=1
else
echo $m
m=$((m+1))
fi
i=$((i+1))
done