#!/usr/bin/env bash
#this to change resolves for facebook.com and localhost
# Backup the original hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Replace localhost and facebook.com entries in the hosts file
sudo sed -i 's/localhost/127.0.0.2/g;' /etc/hosts
echo '8.8.8.8 facebook.com' | sudo tee -a /etc/hosts
