#!/usr/bin/env bash
# some edit for protect my server from hacking
chmod 777  /etc/nginx/nginx.conf
sed -i 's/^user.*;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo pkill -9 apache
sudo service nginx restart
