#!/usr/bin/env bash
# some edit for protect my server from hacking
sed -i 's/# user www-data/user nginx/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 444 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
